[tools]
go = "latest"

[tasks.build]
description = "Builds the project"
run = "go build ."

[tasks.dev]
description = "Runs the project"
run = "go run ."

[tasks.test]
description = "Runs the project"
run = "go test ./..."
